Repository DevCycleHQ/flutter-client-sdk, pull requests merged in 2023-05, with the labels that each got.

#93 [release] 1.3.2
  CHANGELOG.md
  README.md
  android/build.gradle
  pubspec.yaml
Labels: 1 min review

#94 [fix] Pass errors as strings to callbacks
  android/src/main/kotlin/com/devcycle/devcycle_flutter_client_sdk/DevCycleFlutterClientSdkPlugin.kt
  example/lib/main.dart
  lib/devcycle_flutter_client_sdk.dart
Labels: 5 min review

#95 Release 1.3.3
  CHANGELOG.md
  README.md
  pubspec.yaml
Labels: 1 min review

#96 DVC-7156 add variableValue() method, update tests
  lib/devcycle_flutter_client_sdk.dart
  test/devcycle_flutter_client_sdk_test.dart
Labels: 1 min review

#97 DVC-7300 Make DVCVariables non-optional
  example/lib/main.dart
  lib/devcycle_flutter_client_sdk.dart
  lib/devcycle_flutter_client_sdk_method_channel.dart
  lib/devcycle_flutter_client_sdk_platform_interface.dart
  lib/dvc_variable.dart
Labels: 1 min review

#98 [release] 1.4.0
  CHANGELOG.md
  README.md
  android/build.gradle
  ios/devcycle_flutter_client_sdk.podspec
  pubspec.yaml
Labels: 1 min review

#99 chore(release): 1.5.0
  CHANGELOG.md
  README.md
  android/build.gradle
  pubspec.yaml
Labels: 1 min review

#100 chore(release): 1.5.1
  CHANGELOG.md
  android/build.gradle
  pubspec.yaml
Labels: 1 min review

#101 fix: failing tests on new flutter version
  .github/workflows/test.yaml
  test/devcycle_flutter_client_sdk_method_channel_test.dart
  test/devcycle_flutter_client_sdk_test.dart
Labels: 1 min review, safe-changes

#102 chore: fix readme version
  README.md
Labels: 1 min review, safe-changes
